### ISSUE TITLE
issues in README of WildFly Swarm REST API Level 0 .zip booster

### ISSUE THREAD

**Issue by Ladicek** [openshiftio/appdev-documentation#595]
I see a couple of small issues in the generated README in the .zip of the Swarm REST booster. I guess some/most of them are more common than for just this booster.

1. It says "unzip booster-rest-http-wildfly-swarm.zip", but the .zip name is "whatever-artifact-id-i-chose-in-the-wizard.zip".
2. It says "cd booster-rest-http-wildfly-swarm" after unzipping, but the directory is called "whatever-artifact-id-i-chose-in-the-wizard".
3. In "Update this Booster", it says "Stop your booster" but doesn't tell how. (It's Ctrl+C on Linux, not sure about Windows.)
4. It says "mvn clean fabric8:deploy -Popenshift -DskipTests", but there's really no reason to skip the tests. They pass just fine. (They are just local tests, as we don't specify `-Popenshift-it` here.)
5. There's also a section "CI/CD Deployment", which is just wrong for the .zip. But the last sentence "You can also learn more about this booster and rest of the WildFly Swarm runtime in ..." makes sence and should be kept.

**Comment by Ladicek** [comment]
Also the "Next Steps" in the wizard tell me: "unzip wfswarm-rest-http.zip" and "cd wfswarm-rest-http", even though (as I said above) the .zip is called "booster.zip" and the directory in it is called "booster". I'm mentioning it here because I know (I think :-) ) that the text is present in this repo.

**Comment by gastaldi** [comment]
That's a bug in the launchpad-addon. I fixed it in https://github.com/openshiftio/launchpad-addon/commit/1ed9dd72f86633ffd4cf000cc318e2e67696523b

**Comment by gastaldi** [comment]
Thanks for catching that! :+1:

**Comment by Ladicek** [comment]
@gastaldi Will the downloaded .zip file also have correct name and its top-level directory will have correct name? Thanks for the fix!

**Comment by gastaldi** [comment]
@Ladicek yes, you can already see that in https://launch.prod-preview.openshift.io/wizard

**Comment by Ladicek** [comment]
OK thanks @gastaldi. I just checked and the issue in "Next Steps" in the wizard is gone. But the issue in the README remains. So all 5 items in the 1st comment of this issue are still valid.
